name: CI

on:
  push:
    branches:
      - features/theory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.1'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        run: |
          npm run build:prod
          npm install gh-pages
          npx gh-pages -d build -r https://EvgeniyWis:${{ secrets.GH_TOKEN }}@github.com/EvgeniyWis/SuncovRussian.git
